### ISSUE TITLE
Change form submission process so user is not kicked out to Salesforce in Google Analytics

### ISSUE THREAD

**Issue by jessicatelles** [openstax/bit-backlog#21]
Trello: https://trello.com/c/kvl0y4xz/870-change-form-submission-process-so-user-is-not-kicked-out-to-salesforce-in-google-analytics

Description
--
I'd like to re-examine our form submission process for the forms that send data to Salesforce (interest, adoption). Currently, we aren't able to get web behavior information on those users who actually convert/report an adoption because in Google Analytics, we are shown that the user has left the site. They are then reported as a new session when they hit the confirmation form. We are losing very crucial information that would help us make better business decisions; e.g., which emails/websites/combination of actions lead to someone actually reporting an adoption. 

I know this was examined when the website was newer, but I wanted to ask for another explanation in case we could try anything new.

Acceptance
--
- In Google Analytics, we can follow a user from entering the site all the way through completing a form, and eventually exiting the site
- When a user submits a form on OSWeb, they are not reported as exiting the site and then re-entering in a new session from Salesforce

Proposed solution
--
Issue GA event when user submits form

Impact
--
* **Severity**: [ ] High [ ] Medium  [ ] Low

**Comment by jessicatelles** [comment]
Courtney Raymond Oct 11 at 2:20 PM:
What is the status on this? And is any additional info needed from me?

**Comment by meeragovindaraju** [comment]
Issue moved to [openstax/bit #91](https://github.com/openstax/bit/issues/91) via [**ZenHub**](https://www.zenhub.com/)
