### ISSUE TITLE
Accounts should pull book info for Faculty Verification form from the OS CMS

### ISSUE THREAD

**Issue by jessicatelles** [openstax/bit-backlog#23]
Trello: https://trello.com/c/KIxY98pj/943-accounts-should-pull-book-info-for-faculty-verification-form-from-the-os-cms

Description
--
The list of books and their Salesforce code is being hard coded in the Faculty Verification form. Since the same info is in the CMS, we should be pulling the info from there. This will allow new books to automagically appear on the form.

Investigation
--
Talk to @ dante about this.

Acceptance
--
Book info is pulled from the CMS and is no longer hard coded.

Impact
--
* **Severity**: [ ] High [ ] Medium  [ ] Low

**Comment by RoyEJohnson** [comment]
Will be included with updated Faculty Verification Form
