### ISSUE TITLE
Users would like to delete their accounts especially when they have more than one

### ISSUE THREAD

**Issue by jessicatelles** [openstax/bit-backlog#9]
Trello: https://trello.com/c/pLyla1sj/805-users-would-like-to-delete-their-accounts-especially-when-they-have-more-than-one

Description
--
Users often make multiple accounts for various reasons. When told they only really need one, they have requested one of the accounts be deleted. it would be nice to have a delete/ deactivate option especially when it is requested by the users.

Acceptance
-- 

Impact
--
Severity: [ ] High [ ] Medium [ ] Low
CS Case #22895

Design
--
- [ ] UX - Design @Trellouser --- ar:0,?
- [ ] UX - User feedback testing @Trellouser --- ar:0,?

Code
--
- [ ] Role Task @Trellouser --- olp:?,?,? --- ar:0,?
- [ ] UX Approve front-end implementation @Trellouser

Test
-- 
- [ ] QA Test prep @Trellouser --- olp:?,?,? --- ar:0,?
- [ ] QA Test exec @Trellouser --- olp:?,?,? --- ar:0,?

**Comment by allisonhowell** [comment]
Closing this issue and will open a new one once we have more definition from our internal GDPR team.
